### ISSUE TITLE
cant chat or use a command

### ISSUE THREAD

**Issue by mote166** [jackthehack21/koth#10] opened 2019-07-29 20:21 UTC
when in a koth game no one in that game can chat or use a command

pocketmine: 3.9.1

**Comment by jackthehack21** [comment] 2019-07-29 20:37
Players are allowed to chat my plugin does not touch that, commands are blocked by default you can change it in the config file.

**Comment by ZandercraftGames** [comment] 2019-07-29 20:38
I think this was purposeful, since it does accept commands, but only KOTH ones which I understand because it stops the plugin from glitching out if someone uses another plugin to move out of the arena's world or switch gamemodes, but I definitely think chat should be allowed and also that it should send a message to the user saying that non-koth-related commands are disabled whilst in a game, instead of making the user think that their connection has froze/broke.

**Comment by ZandercraftGames** [comment] 2019-07-29 20:39
I also think this issue should have been explored more deeply before closing it, as I can confirm that chat is blocked as well @jackthehack21.

**Comment by jackthehack21** [comment] 2019-07-29 20:41
I need a server.log from someone with the chat issue then.
And for the commands disabled notification ill add it in beta4

**Comment by ZandercraftGames** [comment] 2019-07-29 20:42
Thanks Jack. What level of debugging do you want?

**Comment by jackthehack21** [comment] 2019-07-29 20:42
server.log catches all levels.

**Comment by ZandercraftGames** [comment] 2019-07-29 20:43
Ahh okay. Sorry, I misunderstood it as being "server log".

**Comment by mote166** [comment] 2019-07-29 23:40
ok so it turned out that i had the commands turned off in the config and once i turned it on the chat came back, and as zander said not only commands get blocked, even the chat gets blocked too

**Comment by jackthehack21** [comment] 2019-07-30 07:23
I know what’s causing it, but I need someone’s log to confirm

**Comment by jackthehack21** [comment] 2019-08-03 15:56
Fixed in beta4, option to disable chat has also been added alongside notifying the player they cannot do XYZ while in game.

**Closed by jackthehack21** 2019-08-03 15:56 UTC
Labels: Priority: Medium, Status: Confirmed/Replicated, Type: Bug/Issue
